[build]
  command = "composer install --no-dev && php artisan key:generate"
  publish = "public"

[environment]
  PHP_VERSION = "8.2"
  APP_ENV = "production"
  APP_DEBUG = "false"
  APP_KEY = "base64:Uq5f4lT+nu4kRrNNVySNsx4NgZBxvei5Fdw35MYGGC4=" 
  DB_CONNECTION = "mysql"
  DB_HOST = "127.0.0.1"
  DB_PORT = "3306"
  DB_DATABASE = "pos"
  DB_USERNAME = "root"
  DB_PASSWORD = 

[[plugins]]
  package = "@netlify/plugin-php"
